port : 8080 # your port

database :
  type : "postgres"
  host : "localhost" # your host
  port : 5432 # your port
  username : "postgres" # your username
  password : "your password"
  name : "your database name"

app : 
  is_service : false
  duration: "1h" 

salt : "your salt"
key : "your secret key for admin"